"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productList = [
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 },
    { firstname: 'Ram', lastname: 'Babu', country: 'India', state: 'Karnataka', city: 'Bangalore', address: 'Marthahalli',
        cellnumber: 12345, homenumber: 12345 }
    /*{'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},
    {'id': 1, 'name': 'juice 1', 'description': 'description 1'},*/
];
